---
apiVersion: v1
kind: Service
metadata:
  name: kandula-service
spec:
  selector:
    app: backend
  type: LoadBalancer
  ports:
    - name: http
      port: 80
      targetPort: 5000
      nodePort: 30037
      protocol: TCP
