---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kandula-prod
  labels:
    app: kandula
    env: prod
	ver: 1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: kandula
      env: prod
      ver: "1"
  template:
    metadata:
      labels:
        app: backend
        env: prod
        ver: "1"
    spec:
      containers:
      - name: kuard
        image: index.docker.io/ronnietg/opsschool-kandula-app:latest
        ports:
        - containerPort: 5000
          name: http
          protocol: TCP
